### ISSUE TITLE
idf.py build flash monitor

### ISSUE THREAD

**Issue by Dellason** [ruvnet/RuView#1177]
Commit: 7831f294 (v0.8.2-esp32)
ESP-IDF: v5.3
Toolchain: xtensa-esp-elf 13.2.0
Apple Silicon (M1)

The linker error:
undefined reference to '__ieee754_sqrtf'

**Comment by ruvnet** [comment]
The `__ieee754_sqrtf` undefined reference is a known toolchain/SDK version mismatch. The firmware build is tested against **ESP-IDF v5.4** — v5.3 is missing some math stubs that xtensa-esp-elf 13.2.0 expects.

Please upgrade to ESP-IDF v5.4.x and rebuild. On Apple Silicon, use the ESP-IDF installer and select v5.4 from the version picker, or via `idf_tools.py install` after switching with `idf_tools.py install esp-idf==v5.4.0`. Clean the build directory (`idf.py fullclean`) before re-running.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by ruvnet** [comment]
The `undefined reference to '__ieee754_sqrtf'` error is a known toolchain incompatibility between ESP-IDF v5.3 and the xtensa-esp-elf toolchain on Apple Silicon. The firmware builds against **ESP-IDF v5.4** — v5.3 is not supported.

Fix: switch to the v5.4 branch and reinstall the toolchain:

```bash
cd ~/esp/esp-idf
git checkout v5.4
./install.sh esp32s3
. ./export.sh
```

Then retry `idf.py build`. If you used a manual toolchain install rather than `install.sh`, ensure the `xtensa-esp-elf` version bundled with v5.4 is on your PATH (the v5.3 toolchain ships a different `libm` stub that is missing `__ieee754_sqrtf` on the M1 target).

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by ruvnet** [comment]
The `__ieee754_sqrtf` undefined reference is a known toolchain incompatibility with ESP-IDF v5.3 on Apple Silicon (M1/M2). The project targets ESP-IDF v5.4 — upgrading to v5.4 should resolve this linker error. See the firmware build instructions in the repo for the recommended toolchain setup.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mvanhorn** [comment]
Submitted a fix in https://github.com/ruvnet/RuView/pull/1292.

**Comment by ruvnet** [comment]
Fixed by PR #1292, integrated through #1355. Firmware references now align on ESP-IDF v5.4. Build with 5.4, run `idf.py fullclean`, then rebuild; the release firmware matrix passed. Closing.
