### ISSUE TITLE
crates.io publish blocked: engine needs unpublished worldgraph API, sensing-server needs unpublished wifi-densepose-rufield chain

### ISSUE THREAD

**Issue by ruvnet** [ruvnet/RuView#1334]
While publishing the #1332 version bumps, both crates failed `cargo publish` verification for **pre-existing** reasons (not caused by #1332 — verified against published dep sources):

## wifi-densepose-engine 0.3.1
`src/lib.rs:550` calls `WorldGraph::prune_semantic_states`, which exists in the local `crates/worldgraph` submodule but **not** in the published `wifi-densepose-worldgraph 0.3.1`:
```
error[E0599]: no method named `prune_semantic_states` found for struct `WorldGraph`
```
Engine has drifted from the published worldgraph since 0.3.0 shipped. Unblock: publish a new `wifi-densepose-worldgraph` (own repo, `crates/worldgraph` submodule) containing the method, then bump engine's dep and publish 0.3.1.

## wifi-densepose-sensing-server 0.3.4
Depends on `wifi-densepose-rufield` (added post-0.3.3, ADR-262), which is **not on crates.io**, and which itself path-deps four `vendor/rufield` crates (`rufield-core`/`-provenance`/`-privacy`/`-fusion`) — also unpublished:
```
no matching package named `wifi-densepose-rufield` found
```
Unblock options: (a) publish the rufield v0.1 chain + `wifi-densepose-rufield` (a product decision — rufield is explicitly research-grade with synthetic metrics), or (b) make the rufield integration an off-by-default feature so the crate publishes without it.

Until resolved, main's crate versions (0.3.1 / 0.3.4) are intentionally ahead of crates.io. **Do not publish with `--no-verify`** — the tarballs genuinely don't compile against their declared registry deps.

🤖 Generated with [claude-flow](https://github.com/ruvnet/claude-flow)

**Comment by ruvnet** [comment]
Resolved — the full publish chain is live on crates.io:

| Crate | Version | Notes |
|---|---|---|
| wifi-densepose-worldgraph | 0.3.2 | published from ruvnet/worldgraph (adds `prune_semantic_states`) |
| rufield-core / -provenance / -privacy / -fusion | 0.1.0 | first publish of the RuField MFS chain (research-grade; SYNTHETIC-metric caveats per their own docs) |
| wifi-densepose-engine | 0.3.1 | verifies against worldgraph 0.3.2 |
| wifi-densepose-rufield | 0.3.0 | first publish; path deps now carry `version = "0.1.0"` |
| wifi-densepose-signal | 0.3.5 | registry 0.3.4 predated `resample_to_canonical`/`for_tdm_schedule` — third instance of the same drift pattern |
| wifi-densepose-sensing-server | 0.3.4 | ships #1309/#1310 fixes |

Also fixed along the way: rufield's fusion↔adapters circular dev-dependency (path-only dev-dep, ruvnet/rufield@f3c1492), worldgraph/rufield submodule pointers bumped on main, and a stale-lock true-up (worldmodel and ruview-swarm's removed core dep were still in Cargo.lock).

**Recurring pattern worth a guard**: three crates (engine, signal, worldgraph) had public API added after their version was last published, with no bump — every one was discovered only at publish time. A CI job that runs `cargo publish --dry-run` for published crates whose source changed would catch this at PR time.

🤖 Generated with [claude-flow](https://github.com/ruvnet/claude-flow)
