### PR TITLE
docs: align firmware ESP-IDF version references to v5.4 (fixes #1177 build error)

### LINKED ISSUE #1177: idf.py build flash monitor
Commit: 7831f294 (v0.8.2-esp32)
ESP-IDF: v5.3
Toolchain: xtensa-esp-elf 13.2.0
Apple Silicon (M1)

The linker error:
undefined reference to '__ieee754_sqrtf'

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Align firmware ESP-IDF version references to v5.4 (fixes #1177 build error).

## Why this matters

Issue #1177 reports an ESP32 firmware build failure: `undefined reference to '__ieee754_sqrtf'` when building the CSI-node firmware (commit 7831f294, v0.8.2-esp32) with ESP-IDF v5.3 / xtensa-esp-elf 13.2.0 on Apple Silicon. The owner (ruvnet) replied three times that the project is tested against and targets ESP-IDF v5.4, and that v5.2/v5.3 are missing math stubs (`__ieee754_sqrtf` is pulled in by the `sqrtf` calls in `main/edge_processing.c`), so the fix is to build with v5.4. The root cause on the repo side is a stale documentation inconsistency: the firmware README quickstart still instructs users to build with the `espressif/idf:v5.2` Docker image and carries an "ESP-IDF v5.2" badge, and

## Testing

Changes are scoped to the files named in the fix; added or updated tests where the project has a suite, and matched existing conventions.

Fixes #1177

### CODE REVIEW

**Comment by PrinceAudre** [comment]
The v5.4 target is correct, but these changes appear to be **already on `main`**: `firmware/esp32-csi-node/CMakeLists.txt` already reads `Requires ESP-IDF v5.4+`, and the README badge + docker references are already `v5.4` — there are no `v5.2` references left on current `main`. The `v5.2→v5.4` diff shown here is against a stale merge-base.

So this looks safe to **close as already-resolved** (or it'll need a rebase, after which it applies as a no-op). #1177 already appears addressed on `main`.

**Comment by mvanhorn** [comment]
Confirmed - closing as already-resolved. `firmware/esp32-csi-node/CMakeLists.txt` is byte-identical to current `main`, and the only README difference is that `main` is ahead of this branch (the display-less board note), not behind. There are no `v5.2` references left anywhere in the firmware directory, so #1177 is addressed on `main` already. Thanks for the careful read.
